-- Booking status extensions
ALTER TYPE "BookingRequestStatus" ADD VALUE IF NOT EXISTS 'SCHEDULED';
ALTER TYPE "BookingRequestStatus" ADD VALUE IF NOT EXISTS 'ACTIVE';
ALTER TYPE "BookingRequestStatus" ADD VALUE IF NOT EXISTS 'COMPLETED';

-- Employee module
ALTER TYPE "EmployeeModule" ADD VALUE IF NOT EXISTS 'MANAGER_CONTROL';

-- Audit actions
ALTER TYPE "AuditActionType" ADD VALUE IF NOT EXISTS 'BOOKING_APPROVED';
ALTER TYPE "AuditActionType" ADD VALUE IF NOT EXISTS 'BOOKING_REJECTED';
ALTER TYPE "AuditActionType" ADD VALUE IF NOT EXISTS 'BOOKING_SCHEDULED';
ALTER TYPE "AuditActionType" ADD VALUE IF NOT EXISTS 'BOOKING_STATUS_CHANGED';
ALTER TYPE "AuditActionType" ADD VALUE IF NOT EXISTS 'QUOTE_UPDATED';
ALTER TYPE "AuditActionType" ADD VALUE IF NOT EXISTS 'INVOICE_UPDATED';
ALTER TYPE "AuditActionType" ADD VALUE IF NOT EXISTS 'CATEGORY_UPDATED';
ALTER TYPE "AuditActionType" ADD VALUE IF NOT EXISTS 'CUSTOMER_STATUS_CHANGED';
