-- Additive approval tiers and audit types for access hierarchy
ALTER TYPE "PurchaseRequestStatus" ADD VALUE IF NOT EXISTS 'SUPERVISOR_APPROVED';
ALTER TYPE "LeaveRequestStatus" ADD VALUE IF NOT EXISTS 'SUPERVISOR_APPROVED';
ALTER TYPE "AuditActionType" ADD VALUE IF NOT EXISTS 'PERMISSION_CHANGE';
ALTER TYPE "AuditActionType" ADD VALUE IF NOT EXISTS 'HR_APPROVAL';
ALTER TYPE "AuditActionType" ADD VALUE IF NOT EXISTS 'QUOTE_APPROVED';
ALTER TYPE "AuditActionType" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN_OVERRIDE';
